import time
from datetime import datetime
import requests
import qrcode

##### 运行该程序前，请务必停止运行main程序

def get_bilibili_tokens():
    headers = {
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Referer': 'https://www.bilibili.com/'
    }

    session = requests.Session()
    session.headers.update(headers)

    print("[*] 正在初始化会话并获取 BUVID3...")
    session.get("https://www.bilibili.com/")
    buvid3 = session.cookies.get("buvid3")
    
    if not buvid3:
        try:
            res = session.get("https://api.bilibili.com/x/frontend/finger/spi").json()
            buvid3 = res.get('data', {}).get('b_3', '')
        except Exception:
            buvid3 = ""

    print("[*] 正在请求登录二维码...")
    try:
        qr_res = session.get("https://passport.bilibili.com/x/passport-login/web/qrcode/generate").json()
    except Exception as e:
        print(f"[-] 网络请求失败: {e}")
        return
        
    if qr_res.get("code") != 0:
        print("[-] 获取二维码失败！")
        return

    qr_url = qr_res["data"]["url"]
    qr_key = qr_res["data"]["qrcode_key"]

    print("\n[*] 请使用手机哔哩哔哩扫描下方二维码登录：\n")
    qr = qrcode.QRCode()
    qr.add_data(qr_url)
    qr.print_ascii(invert=True)

    print("\n[*] 正在等待扫码确认...")
    while True:
        try:
            poll_res = session.get(f"https://passport.bilibili.com/x/passport-login/web/qrcode/poll?qrcode_key={qr_key}").json()
        except Exception:
            continue
            
        status_code = poll_res.get("data", {}).get("code")

        if status_code == 0:
            print("\n[+] 登录成功！")
            
            # 提取 Cookie
            cookies_dict = session.cookies.get_dict()
            sessdata = cookies_dict.get("SESSDATA", "")
            bili_jct = cookies_dict.get("bili_jct", "")
            
            # 获取当前时间
            login_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            
            # Step 5: 自动写入 data.py
            with open("data.py", "w", encoding="utf-8") as f:
                f.write(f'# This file was generated by Bilibili automatically.\n')
                f.write(f'SESSDATA = "{sessdata}"\n')
                f.write(f'BILI_JCT = "{bili_jct}"\n')
                f.write(f'BUVID3 = "{buvid3}"\n')
                f.write(f'UPDATE_TIME = "{login_time}"\n')
                
            print("[+] 数据已成功写入并更新至data.py")
            break
            
        elif status_code == 86038:
            print("\n[-] 二维码已过期，请重新运行脚本！")
            break
        elif status_code == 86090:
            print("[*] 扫码成功，请在手机上点击确认...", end="\r")
        elif status_code == 86101:
            pass
            
        time.sleep(2)

if __name__ == "__main__":
    get_bilibili_tokens()