import time
from datetime import datetime
import requests
import qrcode

##### 运行该程序前，请务必停止运行main程序

def get_bilibili_tokens():
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
        'Accept-Language': 'zh-CN,zh;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br',
        'Referer': 'https://www.bilibili.com/',
        'sec-ch-ua': '"Google Chrome";v="131", "Chromium";v="131"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'document',
        'sec-fetch-mode': 'navigate',
        'sec-fetch-site': 'same-site',
        'upgrade-insecure-requests': '1'
    }

    session = requests.Session()
    session.headers.update(headers)

    print("[*] 正在初始化会话并获取设备指纹 Cookie...")
    # 访问主页，B站会在响应头里设置 buvid3、b_nut 等初始 Cookie
    session.get("https://www.bilibili.com/")

    # 获取 buvid4（通过 B站指纹接口）
    buvid4 = ""
    try:
        spi_res = session.get("https://api.bilibili.com/x/frontend/finger/spi").json()
        b_4 = spi_res.get('data', {}).get('b_4', '')
        if b_4:
            session.cookies.set("buvid4", b_4)
            buvid4 = b_4
            print(f"[+] 通过 spi 接口获取 buvid4: {b_4[:30]}...")
    except Exception as e:
        print(f"[-] 获取 buvid4 失败: {e}")

    # 查看当前已获取的 Cookie
    cookies = session.cookies.get_dict()
    buvid3 = cookies.get("buvid3", "")
    b_nut = cookies.get("b_nut", "")
    
    print(f"[*] 当前指纹: buvid3={buvid3[:20]}..., buvid4={buvid4[:20]}..., b_nut={b_nut[:20]}...")

    print("[*] 正在请求登录二维码...")
    try:
        qr_res = session.get("https://passport.bilibili.com/x/passport-login/web/qrcode/generate").json()
    except Exception as e:
        print(f"[-] 网络请求失败: {e}")
        return
        
    if qr_res.get("code") != 0:
        print("[-] 获取二维码失败！")
        return

    qr_url = qr_res["data"]["url"]
    qr_key = qr_res["data"]["qrcode_key"]

    print("\n[*] 请使用手机哔哩哔哩扫描下方二维码登录：\n")
    qr = qrcode.QRCode()
    qr.add_data(qr_url)
    qr.print_ascii(invert=True)

    print("\n[*] 正在等待扫码确认...")
    while True:
        try:
            poll_res = session.get(
                f"https://passport.bilibili.com/x/passport-login/web/qrcode/poll?qrcode_key={qr_key}"
            ).json()
        except Exception:
            continue
            
        status_code = poll_res.get("data", {}).get("code")

        if status_code == 0:
            print("\n[+] 登录成功！")
            
            # 提取所有 Cookie（登录后 B站会下发 SESSDATA、bili_jct、DedeUserID 等）
            final_cookies = session.cookies.get_dict()
            sessdata = final_cookies.get("SESSDATA", "")
            bili_jct = final_cookies.get("bili_jct", "")
            dedeuserid = final_cookies.get("DedeUserID", "")
            
            # 有些 Cookie 可能在登录响应中更新，优先用最新的
            buvid3 = final_cookies.get("buvid3", buvid3)
            buvid4 = final_cookies.get("buvid4", buvid4)
            b_nut = final_cookies.get("b_nut", b_nut)
            
            login_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            
            # 写入 data.py
            with open("data.py", "w", encoding="utf-8") as f:
                f.write(f'# This file was generated by Bilibili automatically.\n')
                f.write(f'SESSDATA = "{sessdata}"\n')
                f.write(f'BILI_JCT = "{bili_jct}"\n')
                f.write(f'BUVID3 = "{buvid3}"\n')
                f.write(f'BUVID4 = "{buvid4}"\n')
                f.write(f'B_NUT = "{b_nut}"\n')
                f.write(f'DEDEUSERID = "{dedeuserid}"\n')
                f.write(f'UPDATE_TIME = "{login_time}"\n')
                
            print("[+] 数据已成功写入 data.py")
            print(f"    SESSDATA:   {sessdata[:20]}...")
            print(f"    BILI_JCT:   {bili_jct[:20]}...")
            print(f"    BUVID3:     {buvid3[:20]}...")
            print(f"    BUVID4:     {buvid4[:20]}...")
            print(f"    B_NUT:      {b_nut[:20]}...")
            print(f"    DEDEUSERID: {dedeuserid}")
            break
            
        elif status_code == 86038:
            print("\n[-] 二维码已过期，请重新运行脚本！")
            break
        elif status_code == 86090:
            print("[*] 扫码成功，请在手机上点击确认...", end="\r")
        elif status_code == 86101:
            pass
            
        time.sleep(2)

if __name__ == "__main__":
    get_bilibili_tokens()